apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kids
  namespace: kids
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - kids.aiacta.com
    secretName: kids-tls
  rules:
  - host: kids.aiacta.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kids
            port:
              number: 80
