apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "kids.fullname" . }}-migration
  labels:
    app: {{ include "kids.fullname" . }}-migration
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      labels:
        app: {{ include "kids.fullname" . }}-migration
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migration
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["bun", "run", "server/migrate-standalone.ts"]
          env:
            - name: DATABASE_URL
              value: "postgres://{{ .Values.postgres.auth.username }}:{{ .Values.postgres.auth.password }}@{{ include "kids.fullname" . }}-postgres:5432/{{ .Values.postgres.auth.database }}"
