apiVersion: v1
kind: Service
metadata:
  name: {{ include "kids.fullname" . }}-postgres
  labels:
    app: {{ include "kids.fullname" . }}-postgres
spec:
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    app: {{ include "kids.fullname" . }}-postgres
  clusterIP: None
