apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "kids.fullname" . }}-postgres
  labels:
    app: {{ include "kids.fullname" . }}-postgres
spec:
  serviceName: {{ include "kids.fullname" . }}-postgres
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "kids.fullname" . }}-postgres
  template:
    metadata:
      labels:
        app: {{ include "kids.fullname" . }}-postgres
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.auth.database }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.auth.username }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.auth.password }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.postgres.persistence.size }}
